
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("image/new", "Create image")) ?>
</div>

<?php echo $this->tag->form(array("image/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search image</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="location">Location</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("location", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
