<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("contact/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("contact/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Content</th>
            <th>Created</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $contact) { ?>
        <tr>
            <td><?php echo $contact->id ?></td>
            <td><?php echo $contact->name ?></td>
            <td><?php echo $contact->email ?></td>
            <td><?php echo $contact->content ?></td>
            <td><?php echo $contact->created_at ?></td>
            <td><?php echo $this->tag->linkTo(array("contact/edit/" . $contact->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("contact/delete/" . $contact->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("contact/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("contact/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("contact/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("contact/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
